apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pos
  template:
    metadata:
      labels:
        app: pos
    spec:
      containers:
        - name: pos-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:pospassword123@my-db-postgresql.default.svc.cluster.local:5432/pos_db"